// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/reply.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DBReply_Status int32

const (
	DBReply_Unknown        DBReply_Status = 0
	DBReply_OK             DBReply_Status = 200
	DBReply_Success        DBReply_Status = 201
	DBReply_InvalidRequest DBReply_Status = 400
	DBReply_NetworkError   DBReply_Status = 450
	DBReply_InternalError  DBReply_Status = 500
)

var DBReply_Status_name = map[int32]string{
	0:   "Unknown",
	200: "OK",
	201: "Success",
	400: "InvalidRequest",
	450: "NetworkError",
	500: "InternalError",
}

var DBReply_Status_value = map[string]int32{
	"Unknown":        0,
	"OK":             200,
	"Success":        201,
	"InvalidRequest": 400,
	"NetworkError":   450,
	"InternalError":  500,
}

func (x DBReply_Status) String() string {
	return proto.EnumName(DBReply_Status_name, int32(x))
}

func (DBReply_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fca2ff5f393a9201, []int{0, 0}
}

type DBReply struct {
	Version              int32          `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Status               DBReply_Status `protobuf:"varint,2,opt,name=status,proto3,enum=pb.DBReply_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DBReply) Reset()         { *m = DBReply{} }
func (m *DBReply) String() string { return proto.CompactTextString(m) }
func (*DBReply) ProtoMessage()    {}
func (*DBReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_fca2ff5f393a9201, []int{0}
}

func (m *DBReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBReply.Unmarshal(m, b)
}
func (m *DBReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBReply.Marshal(b, m, deterministic)
}
func (m *DBReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBReply.Merge(m, src)
}
func (m *DBReply) XXX_Size() int {
	return xxx_messageInfo_DBReply.Size(m)
}
func (m *DBReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DBReply.DiscardUnknown(m)
}

var xxx_messageInfo_DBReply proto.InternalMessageInfo

func (m *DBReply) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *DBReply) GetStatus() DBReply_Status {
	if m != nil {
		return m.Status
	}
	return DBReply_Unknown
}

func init() {
	proto.RegisterEnum("pb.DBReply_Status", DBReply_Status_name, DBReply_Status_value)
	proto.RegisterType((*DBReply)(nil), "pb.DBReply")
}

func init() { proto.RegisterFile("pb/reply.proto", fileDescriptor_fca2ff5f393a9201) }

var fileDescriptor_fca2ff5f393a9201 = []byte{
	// 208 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x48, 0xd2, 0x2f,
	0x4a, 0x2d, 0xc8, 0xa9, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0xda,
	0xc9, 0xc8, 0xc5, 0xee, 0xe2, 0x14, 0x04, 0x12, 0x15, 0x92, 0xe0, 0x62, 0x2f, 0x4b, 0x2d, 0x2a,
	0xce, 0xcc, 0xcf, 0x93, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x82, 0x71, 0x85, 0xb4, 0xb8, 0xd8,
	0x8a, 0x4b, 0x12, 0x4b, 0x4a, 0x8b, 0x25, 0x98, 0x14, 0x18, 0x35, 0xf8, 0x8c, 0x84, 0xf4, 0x0a,
	0x92, 0xf4, 0xa0, 0xda, 0xf4, 0x82, 0xc1, 0x32, 0x41, 0x50, 0x15, 0x4a, 0x19, 0x5c, 0x6c, 0x10,
	0x11, 0x21, 0x6e, 0x2e, 0xf6, 0xd0, 0xbc, 0xec, 0xbc, 0xfc, 0xf2, 0x3c, 0x01, 0x06, 0x21, 0x76,
	0x2e, 0x26, 0x7f, 0x6f, 0x81, 0x13, 0x8c, 0x42, 0x3c, 0x5c, 0xec, 0xc1, 0xa5, 0xc9, 0xc9, 0xa9,
	0xc5, 0xc5, 0x02, 0x27, 0x19, 0x85, 0x84, 0xb9, 0xf8, 0x3c, 0xf3, 0xca, 0x12, 0x73, 0x32, 0x53,
	0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x04, 0x26, 0x30, 0x0b, 0x09, 0x72, 0xf1, 0xf8, 0xa5,
	0x96, 0x94, 0xe7, 0x17, 0x65, 0xbb, 0x16, 0x15, 0xe5, 0x17, 0x09, 0x1c, 0x62, 0x16, 0x12, 0xe2,
	0xe2, 0xf5, 0xcc, 0x2b, 0x49, 0x2d, 0xca, 0x4b, 0xcc, 0x81, 0x88, 0x7d, 0x61, 0x4e, 0x62, 0x03,
	0x7b, 0xc3, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xc6, 0xdf, 0x70, 0x5f, 0xd8, 0x00, 0x00, 0x00,
}
