// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/request.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DBRequest_Verb int32

const (
	DBRequest_Put DBRequest_Verb = 0
	DBRequest_Get DBRequest_Verb = 1
)

var DBRequest_Verb_name = map[int32]string{
	0: "Put",
	1: "Get",
}

var DBRequest_Verb_value = map[string]int32{
	"Put": 0,
	"Get": 1,
}

func (x DBRequest_Verb) String() string {
	return proto.EnumName(DBRequest_Verb_name, int32(x))
}

func (DBRequest_Verb) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_830d9371e697e3ea, []int{0, 0}
}

type DBRequest struct {
	Version              int32          `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Verb                 DBRequest_Verb `protobuf:"varint,2,opt,name=verb,proto3,enum=pb.DBRequest_Verb" json:"verb,omitempty"`
	DbName               string         `protobuf:"bytes,3,opt,name=dbName,proto3" json:"dbName,omitempty"`
	TableName            string         `protobuf:"bytes,4,opt,name=tableName,proto3" json:"tableName,omitempty"`
	StartKey             string         `protobuf:"bytes,5,opt,name=startKey,proto3" json:"startKey,omitempty"`
	Data                 []byte         `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DBRequest) Reset()         { *m = DBRequest{} }
func (m *DBRequest) String() string { return proto.CompactTextString(m) }
func (*DBRequest) ProtoMessage()    {}
func (*DBRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_830d9371e697e3ea, []int{0}
}

func (m *DBRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBRequest.Unmarshal(m, b)
}
func (m *DBRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBRequest.Marshal(b, m, deterministic)
}
func (m *DBRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBRequest.Merge(m, src)
}
func (m *DBRequest) XXX_Size() int {
	return xxx_messageInfo_DBRequest.Size(m)
}
func (m *DBRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DBRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DBRequest proto.InternalMessageInfo

func (m *DBRequest) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *DBRequest) GetVerb() DBRequest_Verb {
	if m != nil {
		return m.Verb
	}
	return DBRequest_Put
}

func (m *DBRequest) GetDbName() string {
	if m != nil {
		return m.DbName
	}
	return ""
}

func (m *DBRequest) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

func (m *DBRequest) GetStartKey() string {
	if m != nil {
		return m.StartKey
	}
	return ""
}

func (m *DBRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterEnum("pb.DBRequest_Verb", DBRequest_Verb_name, DBRequest_Verb_value)
	proto.RegisterType((*DBRequest)(nil), "pb.DBRequest")
}

func init() { proto.RegisterFile("pb/request.proto", fileDescriptor_830d9371e697e3ea) }

var fileDescriptor_830d9371e697e3ea = []byte{
	// 198 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8f, 0xb1, 0x4a, 0xc7, 0x30,
	0x10, 0xc6, 0xcd, 0xbf, 0x69, 0x6b, 0x0f, 0x91, 0x72, 0x83, 0x04, 0x71, 0x08, 0x1d, 0x24, 0x53,
	0x04, 0x7d, 0x03, 0x11, 0x1c, 0x04, 0x91, 0x0c, 0xee, 0x39, 0x7a, 0x83, 0xa0, 0x36, 0xa6, 0xd7,
	0x82, 0x0f, 0xe9, 0x3b, 0x49, 0xa3, 0xd6, 0xed, 0xfb, 0x7d, 0x3f, 0x8e, 0xe3, 0x83, 0x3e, 0xd1,
	0x55, 0xe6, 0x8f, 0x85, 0x67, 0xf1, 0x29, 0x4f, 0x32, 0xe1, 0x21, 0xd1, 0xf0, 0xa5, 0xa0, 0xbb,
	0xbb, 0x0d, 0x3f, 0x3d, 0x1a, 0x68, 0x57, 0xce, 0xf3, 0xcb, 0xf4, 0x6e, 0x94, 0x55, 0xae, 0x0e,
	0x7f, 0x88, 0x97, 0xa0, 0x57, 0xce, 0x64, 0x0e, 0x56, 0xb9, 0xd3, 0x6b, 0xf4, 0x89, 0xfc, 0x7e,
	0xe6, 0x9f, 0x39, 0x53, 0x28, 0x1e, 0xcf, 0xa0, 0x19, 0xe9, 0x31, 0xbe, 0xb1, 0xa9, 0xac, 0x72,
	0x5d, 0xf8, 0x25, 0xbc, 0x80, 0x4e, 0x22, 0xbd, 0x72, 0x51, 0xba, 0xa8, 0xff, 0x02, 0xcf, 0xe1,
	0x78, 0x96, 0x98, 0xe5, 0x81, 0x3f, 0x4d, 0x5d, 0xe4, 0xce, 0x88, 0xa0, 0xc7, 0x28, 0xd1, 0x34,
	0x56, 0xb9, 0x93, 0x50, 0xf2, 0x60, 0x40, 0x6f, 0x3f, 0xb1, 0x85, 0xea, 0x69, 0x91, 0xfe, 0x68,
	0x0b, 0xf7, 0x2c, 0xbd, 0xa2, 0xa6, 0x4c, 0xbb, 0xf9, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x87, 0x15,
	0x42, 0xf8, 0xee, 0x00, 0x00, 0x00,
}
